package de.android.fuellog.util;

public interface Values {

	int QUIT_APPLICATION = 1;

	String QUIT_APP_RESULT = "QUIT";

	int EURO_LITER_KM = 0;
	int EURO_LITER_MILES = 1;
	int EURO_USGALLONS_KM = 2;
	int EURO_USGALLONS_MILES = 3;
	int EURO_UKGALLONS_KM = 4;
	int EURO_UKGALLONS_MILES = 5;

	int DOLLAR_USGALLONS_KM = 6;
	int DOLLAR_USGALLONS_MILES = 7;
	int DOLLAR_UKGALLONS_KM = 8;
	int DOLLAR_UKGALLONS_MILES = 9;
	int DOLLAR_LITER_KM = 10;
	int DOLLAR_LITER_MILES = 11;

	int POUNDS_USGALLONS_KM = 12;
	int POUNDS_USGALLONS_MILES = 13;
	int POUNDS_UKGALLONS_KM = 14;
	int POUNDS_UKGALLONS_MILES = 15;
	int POUNDS_LITER_KM = 16;
	int POUNDS_LITER_MILES = 17;
}
